services:
  backend:
    build:
      context: ./EDTECH-BACK/edtech-api
    container_name: edtech_backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongo:27017/edtech_db?authSource=admin
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - insta-net

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - insta-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - insta-net

networks:
  insta-net:
    driver: bridge

volumes:
  mongo_data: